import { Page, View, Text, StyleSheet } from "@react-pdf/renderer";
import { PDF_COLORS, PDF_FONTS, PAGE_MARGIN } from "@/lib/pdf-theme";
import { PdfOrnamentDivider } from "../shared/pdf-ornament";

const styles = StyleSheet.create({
  page: {
    paddingTop: PAGE_MARGIN.top,
    paddingBottom: PAGE_MARGIN.bottom,
    paddingLeft: PAGE_MARGIN.left,
    paddingRight: PAGE_MARGIN.right,
    backgroundColor: PDF_COLORS.background,
    justifyContent: "center",
  },
  title: {
    fontSize: 18,
    fontWeight: 700,
    color: PDF_COLORS.primary,
    fontFamily: PDF_FONTS.story,
    textAlign: "center",
    marginBottom: 30,
  },
  statsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 16,
    marginBottom: 30,
  },
  statCard: {
    width: "40%",
    padding: 16,
    backgroundColor: PDF_COLORS.card,
    borderRadius: 8,
    border: `0.5pt solid ${PDF_COLORS.border}`,
    alignItems: "center",
  },
  statNumber: {
    fontSize: 28,
    fontWeight: 700,
    color: PDF_COLORS.primary,
    fontFamily: PDF_FONTS.heading,
  },
  statLabel: {
    fontSize: 9,
    color: PDF_COLORS.muted,
    fontFamily: PDF_FONTS.body,
    marginTop: 4,
  },
  closingText: {
    fontSize: 14,
    color: PDF_COLORS.foreground,
    fontFamily: PDF_FONTS.story,
    textAlign: "center",
    marginTop: 20,
    lineHeight: 1.8,
  },
  footer: {
    position: "absolute",
    bottom: 40,
    left: 0,
    right: 0,
    textAlign: "center",
    fontSize: 7,
    color: PDF_COLORS.muted,
    fontFamily: PDF_FONTS.body,
  },
});

export interface DiaryStats {
  memberCount: number;
  storyCount: number;
  photoCount: number;
  eventCount: number;
  mostActiveMonth?: string;
}

interface StatsClosingPageProps {
  stats: DiaryStats;
  year: number;
  familyName: string;
}

export function StatsClosingPage({ stats, year, familyName }: StatsClosingPageProps) {
  return (
    <Page size="A4" style={styles.page}>
      <Text style={styles.title}>{year}년을 돌아보며</Text>

      <View style={styles.statsGrid}>
        <View style={styles.statCard}>
          <Text style={styles.statNumber}>{stats.memberCount}</Text>
          <Text style={styles.statLabel}>가족 구성원</Text>
        </View>
        <View style={styles.statCard}>
          <Text style={styles.statNumber}>{stats.storyCount}</Text>
          <Text style={styles.statLabel}>이야기</Text>
        </View>
        <View style={styles.statCard}>
          <Text style={styles.statNumber}>{stats.photoCount}</Text>
          <Text style={styles.statLabel}>사진</Text>
        </View>
        <View style={styles.statCard}>
          <Text style={styles.statNumber}>{stats.eventCount}</Text>
          <Text style={styles.statLabel}>이벤트</Text>
        </View>
      </View>

      {stats.mostActiveMonth && (
        <Text style={{ fontSize: 9, color: PDF_COLORS.muted, fontFamily: PDF_FONTS.body, textAlign: "center" }}>
          가장 활발한 달: {stats.mostActiveMonth}
        </Text>
      )}

      <PdfOrnamentDivider />

      <Text style={styles.closingText}>
        이야기는 계속됩니다...
      </Text>

      <Text style={styles.footer}>
        Generated by 우리家 이야기 · {familyName}
      </Text>
    </Page>
  );
}
